= Pkl LSP

This is an implementation of the link:https://microsoft.github.io/language-server-protocol/[Language Server Protocol]
for link:https://pkl-lang.org[Pkl].

== Features

* [x] Diagnostics (WIP)
* [x] Hover
* [x] Go to definition
* [x] Auto complete (WIP: definition level access still needed)
* [x] Project syncing
* [x] Package downloading
* [ ] Rename
* [ ] Find references
* [ ] Code lens
* [ ] Formatting
* [x] Type checking
* [ ] Quick fixes

== Development

=== Debugging the LSP

The easiest way to start and debug the LSP is to use the `org.pkl.lsp.devlauncher.MainKt.main` entrypoint.

This will open an instance of VSCode as an extension host, with the pkl-vscode plugin installed.
This extension host then connects to the running Java instance.

By default, the launcher opens the https://github.com/apple/pkl-pantry[pkl-pantry] repo, and assumes it is checked out as a sibling repo.
This behavior can be configured with CLI flags; take a look at the link:src/devLauncher/kotlin/org/pkl/lsp/devlauncher/Launcher.kt[source code] for more details.

This expects that the https://github.com/apple/pkl-vscode[pkl-vscode] repo is checked out, and placed right next to this repo on the file system.
It also expects that pkl-vscode is already built.
To build pkl-vscode, run `npm run build:local`.

This also expects that the https://code.visualstudio.com/docs/editor/command-line[`code` cli] is installed, and available on `PATH`.

Note that stopping the launcher will not close the VSCode extension host.
However, restarting the launcher will relaunch the same extension host window.
