= Integrating with Pkl Language Server

Pkl Language Server is a low-level tool that is meant to be integrated with editors by way of plugins.

The documentation below is intended for plugin implementors.

== Distribution

Pkl Language Server is published to https://central.sonatype.com/artifact/org.pkl-lang/pkl-lsp[Maven Central], and also as releases on https://github.com/apple/pkl-lsp/releases[GitHub].

It is recommended that the jar file be bundled into an editor plugin's package contents.

== Running Pkl Language Server

To run the server, provide the jar as an argument to Java.
For example:

[source,shell]
----
java -jar path/to/pkl-lsp.jar
----

Pkl Language Server requires Java 22 or higher.

[NOTE]
====
We plan on providing native binaries in the future.

Follow https://github.com/apple/pkl-lsp/issues/60[#60] to stay updated on its progress.
====

== `pkl-lsp` URI scheme

The server uses the `pkl-lsp` scheme to represent sources from the standard library, as well as other types of non-file Pkl sources.

For example, the `pkl:base` standard library module is surfaced to editors as URI `pkl-lsp://stdlib/base.pkl`.

== Custom client options

When starting the server, additional client options can be provided to configure the behavior of the language server.

These options are provided in the `initializationOptions` section of the link:https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeParams[Initialize Request].


=== `renderOpenFileCommandInDocs`

Type: `Boolean`

Cause the server to render links within documentation using the `command:pkl.open.file` URI.

If enabled, clients are expected to implement the command <<open-file-command,`pkl.open.file`>>.

[[extended-client-capabilities]]
=== `extendedClientCapabilities`

Tell the server that the client supports additional capabilities made available by Pkl Language Server.

|===
|Name |Description

|`actionableRuntimeNotifications`
|The client supports the `pkl/actionableNotification` message.

|[[configureCommand]] `pklConfigureCommand`
|The client supports the `pkl.configure` command.
|===

== Configuration Requests

Some settings are fetched using the https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration[`workspace/configuration` request], if supported by the client:

The language server uses "Pkl" for its scope URI.

|===
|Name | Type | Description | Default

|`pkl.cli.path`
|String
|The path for the configured Pkl CLI.
|Determined by looking in `$PATH`

|`pkl.formatter.grammarVersion`
|Int (`1` or `2`)
|The grammar version to use when formatting Pkl code.
|`2`
|===

== Additional message types

Pkl Language Server extends the https://microsoft.github.io/language-server-protocol/[Language Server Protocol] with custom message types.

These message types are optional, and enhance the integration with an editor.

[[file-contents-request]]
=== File Contents Request

Method: `pkl/fileContents`

Body: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentIdentifier[`TextDocumentIdentifier`]

Read text contents of the document identified by the specified params..

[[download-package-request]]
=== Download Package Request

Method: `pkl/downloadPackage`

Body: `String`

Download the specified package.

[[sync-projects]]
=== Sync Projects Request

Method: `pkl/syncProjects`

Body: `Any`

Sync any `PklProject` defined in the workspace.
This allows the server to understand imports declared using xref:main:language-reference:index.adoc#dependency-notation[dependency notation].

== Commands

The following commands can optionally be implemented.
If implemented, and the <<extended-client-capabilities,capability>> is made known to Pkl Language Server, the server will issue https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_executeCommand[Execute Command] requests.

|===
|Name | Arguments | Description

|[[open-file-command]] `pkl.open.file`
|`[uri: String, line: Int?, column: Int?]`
|Send a <<file-contents-request>> to Pkl Language Server, and open the resulting contents in an editor pane at the indicated line and column.

|`pkl.syncProjects`
| `<none>`
|Send a <<sync-projects>> to Pkl Language Server.

|`pkl.configure`
| `[configurationPath: string]`
|Open the editor's settings/configuration panel at the configuration path.

|`pkl.downloadPackage`
|`[packageUri: string]`
|Send a <<download-package-request>> to Pkl Language Server.
|===
